package courier.security

import java.io.File
import kotlin.test.AfterTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNull
import kotlin.test.assertTrue

class FileChecksumTest {

    private val tempFiles = mutableListOf<File>()

    @AfterTest
    fun cleanUp() {
        tempFiles.forEach { runCatching { it.delete() } }
    }

    private fun tempFile(content: String): File {
        val f = File.createTempFile("courier-checksum-", ".bin").also { tempFiles += it }
        f.writeText(content)
        return f
    }

    /** Known-answer test: SHA-256 of "abc". */
    @Test
    fun `sha256 matches the published digest for a known input`() {
        val file = tempFile("abc")
        assertEquals(
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
            FileChecksum.sha256(file)
        )
    }

    @Test
    fun `sha256 streams correctly across buffer boundaries`() {
        // Larger than the 64 KB read buffer, so a digest that only hashed the
        // first block would disagree with one that hashed everything.
        val big = tempFile("x".repeat(200_000))
        val expected = FileChecksum.sha256(big)

        assertEquals(64, expected.length)
        // Same content, computed again, must agree.
        assertEquals(expected, FileChecksum.sha256(tempFile("x".repeat(200_000))))
        // Different content must not.
        assertTrue(expected != FileChecksum.sha256(tempFile("x".repeat(199_999))))
    }

    @Test
    fun `matches is tolerant of case and whitespace but not of a missing hash`() {
        val file = tempFile("abc")
        val hash = "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"

        assertTrue(FileChecksum.matches(file, hash))
        assertTrue(FileChecksum.matches(file, hash.uppercase()))
        assertTrue(FileChecksum.matches(file, "  $hash\n"))

        // "Nothing to check against" must never read as verified.
        assertFalse(FileChecksum.matches(file, null), "null expectation must not verify")
        assertFalse(FileChecksum.matches(file, ""), "empty expectation must not verify")
        assertFalse(FileChecksum.matches(file, "   "), "blank expectation must not verify")
        assertFalse(FileChecksum.matches(file, "deadbeef"), "short hash must not verify")
        assertFalse(
            FileChecksum.matches(file, "z".repeat(64)),
            "non-hex of the right length must not verify"
        )
        assertFalse(FileChecksum.matches(file, "0".repeat(64)), "wrong hash must not verify")
    }

    /**
     * The real yt-dlp listing contains both `yt-dlp.exe` and `yt-dlp_x86.exe`.
     * A prefix or `contains` match would return whichever came first, which is
     * how a verifier ends up checking the right file against the wrong hash.
     */
    @Test
    fun `findInSumsFile matches the filename exactly`() {
        val sums = """
            66674953fe251b89f4d08c5f0e35e0728679bd67ab3d7d05c0562af101dd3e7a  yt-dlp.exe
            a8f91bd41452506bc81ebd2f369b186fea0ee7075413ba00cef9fd346a0a5d0c  yt-dlp_x86.exe
        """.trimIndent()

        assertEquals(
            "66674953fe251b89f4d08c5f0e35e0728679bd67ab3d7d05c0562af101dd3e7a",
            FileChecksum.findInSumsFile(sums, "yt-dlp.exe")
        )
        assertEquals(
            "a8f91bd41452506bc81ebd2f369b186fea0ee7075413ba00cef9fd346a0a5d0c",
            FileChecksum.findInSumsFile(sums, "yt-dlp_x86.exe")
        )
    }

    /**
     * The FFmpeg-Builds listing distinguishes shared from static builds only by
     * a suffix, so the same exact-match requirement applies.
     */
    @Test
    fun `findInSumsFile does not confuse a shared build for a static one`() {
        val sums = """
            6d9bb137b273d1e9d9cd9f83471911a4261c22c472ec574a4b3f0679aa5641c0  ffmpeg-N-126390-g9fc8c785e2-win64-gpl-shared.zip
            ee698ac088ce89b3e18ecdef48e71748af5dc8e69d93bcbdcb58e9931ac4d3f3  ffmpeg-N-126390-g9fc8c785e2-win64-gpl.zip
        """.trimIndent()

        assertEquals(
            "ee698ac088ce89b3e18ecdef48e71748af5dc8e69d93bcbdcb58e9931ac4d3f3",
            FileChecksum.findInSumsFile(sums, "ffmpeg-N-126390-g9fc8c785e2-win64-gpl.zip"),
            "Returned the shared build's hash for the static build"
        )
    }

    @Test
    fun `findInSumsFile handles binary markers comments and blank lines`() {
        val sums = """
            # generated by sha256sum

            ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad *payload.zip
        """.trimIndent()

        assertEquals(
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
            FileChecksum.findInSumsFile(sums, "payload.zip")
        )
    }

    @Test
    fun `findInSumsFile returns null rather than guessing`() {
        val sums = "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad  other.zip"

        assertNull(FileChecksum.findInSumsFile(sums, "payload.zip"), "unlisted file must not match")
        assertNull(FileChecksum.findInSumsFile("", "payload.zip"), "empty listing must not match")
        assertNull(
            FileChecksum.findInSumsFile("not a sums file at all", "payload.zip"),
            "malformed listing must not match"
        )
        assertNull(
            FileChecksum.findInSumsFile("tooshort  payload.zip", "payload.zip"),
            "a hash of the wrong length must not be returned"
        )
    }
}
